### ISSUE TITLE
This repo is amazing! Do you plan to support concepts_lists.json?

### ISSUE THREAD

**Issue by swcrazyfan** [giannisdaras/multires_textual_inversion#1]
Hey!

Thanks for your amazing work. I've been experimenting with Dreambooth, and training multiple concepts at once has become very powerful for me. Do you plan to add support for this?

Thanks!

**Comment by giannisdaras** [comment]
Thanks a lot for your interest! For the next month, I am not planning on updating this project -- ICML is coming up and my schedule is very busy. Would be happy to merge any PRs if you are willing to help though!

Thanks!
